[mcp_servers.github]
command = "npx"
args = [
    "-y",
    "@modelcontextprotocol/server-github",
]

[mcp_servers.github.env]
GITHUB_PERSONAL_ACCESS_TOKEN = "github_pat_11CDCSL7Q0dqFiYmXJZlEY_hYU7TQIjOG1zLKXemszwXEDN2bRUazqjiUuuQeeWbZHHI2UW7COjeiQECd"

[mcp_servers.playwright]
command = "npx"
args = [
    "-y",
    "@modelcontextprotocol/server-playwright",
]
